from pathlib import Path

FREE_PROFILE_LIMIT = 5
RECOMMENDED_EXTRA_PROFILE_PRICE_KRW = 2900
RECOMMENDED_EXTRA_PROFILE_BUNDLE_KRW = 6900
TOTAL_MEDIA_LIMIT_BYTES = 1024 * 1024 * 1024
DAILY_VIDEO_LIMIT_BYTES = 100 * 1024 * 1024
MAX_IMAGE_UPLOAD_BYTES = 20 * 1024 * 1024
MAX_VIDEO_UPLOAD_BYTES = 50 * 1024 * 1024
QUESTION_PERMISSION_VALUES = {"none", "members", "any"}
VISIBILITY_MODE_VALUES = {"private", "link_only", "search"}
REPORT_TARGET_TYPES = {"user", "profile", "career", "question", "message", "upload"}
MODERATION_STATUS_VALUES = {"pending", "approved", "rejected"}
MEDIA_KIND_VALUES = {"image", "video", "file"}
AUTO_HIDE_QUESTION_REPORT_THRESHOLD = 3
AUTO_FLAG_UPLOAD_REPORT_THRESHOLD = 3
AUTO_PRIVATE_PROFILE_REPORT_THRESHOLD = 5
QUESTION_MIN_LENGTH = 3
REPORT_REASON_MIN_LENGTH = 3
CHAT_MEDIA_MONTHLY_FREE_LIMIT_BYTES = 100 * 1024 * 1024
PHONE_CODE_EXPIRE_MINUTES = 10
AUTO_WARN_USER_REPORT_THRESHOLD = 3
AUTO_SUSPEND_USER_REPORT_THRESHOLD = 5
ACCOUNT_STATUS_VALUES = {"active", "warned", "suspended"}
TURNSTILE_VERIFY_URL = "https://challenges.cloudflare.com/turnstile/v0/siteverify"
STATIC_PROFILE_DIR = Path(__file__).resolve().parents[1] / "static" / "public_profiles"
STATIC_PROFILE_DIR.mkdir(parents=True, exist_ok=True)
